---
- name: Install chkrootkit
  apt:
    name: chkrootkit
    cache_valid_time: 3600
    state: present
  tags:
    - install
    - chkrootkit
    - chkrootkit-install

- name: Configure /etc/chkrootkit.conf
  template:
    src: "etc/chkrootkit.conf.j2"
    dest: /etc/chkrootkit.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - chkrootkit
    - chkrootkit-configuration
